# Generated by Django 3.0.1 on 2020-01-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200102_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='image',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
