# Generated by Django 3.0.1 on 2020-01-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_premiumbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumbanner',
            name='header_text',
        ),
        migrations.RemoveField(
            model_name='premiumbanner',
            name='text',
        ),
        migrations.RemoveField(
            model_name='premiumbanner',
            name='url_link',
        ),
        migrations.AddField(
            model_name='premiumbanner',
            name='header_text1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='premiumbanner',
            name='header_text2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='premiumbanner',
            name='text1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='premiumbanner',
            name='text2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='premiumbanner',
            name='url_link1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='premiumbanner',
            name='url_link2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
